version: 2
jobs:
  build:
    working_directory: ~/dist

    docker:
      - image: docker

    steps:
      - checkout

      - setup_remote_docker

      - run: |
          docker-compose build
          docker-compose up -d

      - run: |
          docker-compose ps
