version: 2
jobs:
  build:
    working_directory: ~/project

    docker:
      - image: php:7.1

      - image: percona:5.7.17
        environment:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: hw
          MYSQL_USER: hwuser
          MYSQL_PASSWORD: hwpass

      - image: rabbitmq:3.6

    steps:
      - checkout
      - run:
          name: "Install composer"
          command: |
            service --status-all
            php -v
