version: 2
jobs:
  build:
    working_directory: ~/dist

    docker:
      - image: composer

      - image: percona:5.7.17
        environment:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: hw
          MYSQL_USER: hwuser
          MYSQL_PASSWORD: hwpass

      - image: rabbitmq:3.6

    steps:
      - checkout
      - run:
          name: "Check php version"
          command: |
            php -i
            php -v
            pwd
            php -r 'echo __DIR__;'

#      - run:
#          name: "Install composer"
#          command: |
#            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#            php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
#            php composer-setup.php
#            php -r "unlink('composer-setup.php');"
      - restore_cache:
          key: video-market-api-{{ .Branch }}-{{ checksum "composer.json" }}

      - run:
          name: "Run composer"
          command: |
            composer install

      - save_cache:
          key: video-market-api-{{ .Branch }}-{{ checksum "composer.json" }}
          paths:
            - "~/vendor"
            - "~/composer.lock"

      - run:
          name: "start phpunit"
          command: vendor/bin/phpunit -c phpunit.xml.dist